version: '3'
services:
  nb:
      build: .
      command: ["./cmd/todolist/main"]
      restart: always
      ports:
        - "8080:8080"
      networks:
        - web_app
      depends_on:
        - db
  db:
    image: mongo:latest
    container_name: mongo_ct
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - db-data:/data/db
networks:
  web_app:
    driver: bridge
volumes:
  db-data:
    driver: local